<?php

use Illuminate\Database\Seeder;
use App\Models\InsuranceProvider;

class InsuranceProvidersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            'PARTICULAR',
            'CON SALUD.CONV OSSEG',
            'ANDAR PLAN PLUS',
            'ANDAR PLAN BASICO',
            'APTM',
            'ASISTENCIA',
            'ATSA',
            'BANCARIOS',
            'BANCARIOS SOLIDARIDAD',
            'CAMIONEROS',
            'CON SALUD',
            'CONSALUD - CONV. CAM. COMERCIO',
            'CON SALUD - PART.',
            'CON SALUD - CONV.OSFENT',
            'CON SALUD - OSPAT',
            'DIBA',
            'DOCTHOS',
            'FEDECOOP',
            'FEDECOOP - OSPRERA',
            'GASTRONOMICOS',
            'IAMIP PLAN DORADO',
            'IAMIP - A',
            'IAMIP - CONVENIOS',
            'IAMIP - LYF',
            'IAMIP - OSBA',
            'IAMIP - PART',
            'IAMIP - PLATINO',
            'IAMIP - U',
            'IAMIP - VARIOS',
            'IAMIP - SPF',
            'IOSCOR',
            'IOSE',
            'IPS',
            'IPS - PAMI',
            'IPS - ATSA',
            'LUZ Y FUERZA',
            'LUZ Y FUERZA - CONV. IAMIP',
            'LUZ Y FUERZA - CONV.',
            'MEDICUS',
            'MEDIFE OBLIGATORIO',
            'OSBA BANCARIOS',
            'OSDE',
            'OSDE F2',
            'OSDE F1',
            'OSDE 310',
            'OSDE 410',
            'OSECAC',
            'OSFA',
            'OSFFENTOS CONV.',
            'OSME',
            'OSME - IAMIP',
            'OSPAG',
            'OSPAG',
            'OSPAT',
            'OSPAT - CONV.',
            'OSPEC',
            'OSPHAG',
            'OSPHAG',
            'OSPI',
            'OSPIA',
            'OSPIM',
            'OSPIT',
            'OSPLAD',
            'OSPRERA',
            'OSPSIP',
            'OSSEG - SEGURIDAD',
            'OSSPAT',
            'OSTEL',
            'OSTYR',
            'OSUTGRA',
            'PAMI',
            'PAMI',
            'PODER JUDICIAL',
            'POLICIA FEDERAL',
            'PREST. SANA. BANCARIOS',
            'SACRA',
            'SAMA',
            'SEGUROS',
            'SMATA',
            'SMAUNAM',
            'SMAUNAM PLAN A',
            'SOLIDARIDAD',
            'SPF CONV. IAMIP',
            'UNION PERSONAL',
            'UNION PERSONAL - CONV.',
            'UOM',
            'UP',
            'UP - IPS',
            'UPCN',
            'UTA',
            'MM',
            'CERAMISTAS',
            'GERDANNA SALUD',
            'FED. DE LA CARNE',
            'DOMIN',
            'O.S.PE.PA. C. Y Q.',
            'NO DISPONIBLE',
            'OMINT',
            'YERBATEROS-J.A',
            'PREST.SANT.C/ PERS.MARIT.',
            'OSPRERA MONOT.',
            'JERARQUICOS SALUD',
            'IAMIP - MEDICOS',
            'OSDE F3',
            'APTM-MUT. CONV',
            'OSETRA',
            'INST.SERV.SOC.(BANCARIOS)',
            'OSDO',
            'FERROVIARIOS',
            'PAMI AMBULATORIO',
            'PAMI INTERNADOS',
            'OSFE (FERROVIARIOS)',
            'SOMU.PERS.NAV.',
            'OSAPM (PROP. MEDICA)',
            'MEDIFE VOLUNTARIO',
            'NOSIGLIA SALUD',
            'OSPES',
            'IPS-MISIONES SALUD',
            'OSPERYHRA',
            'OSALARA (AG.DE LOTERIAS)',
            'O.S.E.A.M (MARITIMOS)',
            'MISIONES SALUD',
            'OSPF (FARMACIA)',
            'MOSAISTAS',
            'CAMARA DEL TABACO DE MNES',
            'O.S.P.E.D.YC',
            'OSPECON',
            'SWISS MEDICAL',
            'SI.CO.NA.RA.',
            'O.S.P.BARRACAS',
            'OSTRAC',
            'AUSTRAL OMI',
            'CON SALUD-OSPACA',
            'P.T.O.S',
            'OSPIDA(IMPRENTA)',
            'VISITAR',
            'VISITAR',
            'MEDIFE PLAN AZUL',
            'OSMATA(CON SALUD)',
            'GALENO',
            'ANDAR PLAN CLASICO',
            'O.S.P.E',
            'AGUA Y ENERGIA CAP.FED',
            'O.S.E.I.V',
            'CON SALUD-SMATA',
            'ACCORD SALUD',
            'COVER SALUD',
            'O.S.FOT (FOTOGRAFOS)',
            'OSPAT',
            'O.S.S.A.C.R.A',
            'PAMI EXTRACAPITA',
            'PAMI EXTRACAPITA',
            'PAMI EXTRACAPITA',
            'CO',
            'MEDIFE PLATA',
            'EUROSALUD',
            'MUTUAL DEL CLERO'
        ];

        foreach($items as $item)
        {
            InsuranceProvider::create([
                'name' => $item,
                'percentage' => 0,
                'is_active' => 1
                ]);
        }
    }
}
