<?php

use App\Models\Pathology;
use Illuminate\Database\Seeder;

class PathologiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $patologias = [
            'CANCER DE CERVIX ESTADIO I',
            'CANCER DE CERVIX ESTADIO II',
            'CANCER DE CERVIX ESTADIO III-IV',
            'CANCER DE COLON DUKES A',
            'CANCER DE COLON DUKES B',
            'CANCER DE COLON DUKES C',
            'CANCER DE COLON DUKES D',
            'CANCER DE VULVA Y VAGINA',
            'CANCER DE OVARIO',
            'ENFERMEDAD TROFOBLASTICA',
            'LESION LITICA',
            'CANCER DE VEJIGA T URINARIO',
            'SEMINOMA',
            'T NO SEMINOMATOSO',
            'CANCER DE PROSTATA',
            'CANCER DE PULMON NSC',
            'CANCER DE PULMON SC',
            'CANCER DE ESOFAGO',
            'CANCER FOLICULAR DE TIROIDES',
            'CANCER DE PANCREAS Y VIAS BILIARES',
            'NO ONCOLOGICO',
            'SARCOMA DE PARTES BLANDAS',
            'OSTEOSARCOMA Y SARCOMA DE EWING',
            'CONDROSARCOMAS',
            'TUMORES CEREBRALES PRIMARIOS',
            'METASTASIS SNC',
            'POD',
            'CANCER DE LABIO Y CAVIDAD ORAL',
            'CANCER DE FARINGE',
            'CANCER DE LARINGE',
            'CANCER DE SENOS PARANASALES Y GLANDULAS SALIVALES.',
            'CANCER DE TIROIDES',
            'MESOTELIOMAS',
            'CANCER DE RECTO Y ANO',
            'CANCER DE MAMA ESTADIO I',
            'CANCER DE MAMA ESTADIO II',
            'CANCER DE MAMA ESTADIO III',
            'CANCER DE MAMA ESTADIO IV',
            'TUMORES DE ORBITA',
            'CANCER DE PENE',
            'MIELOMA',
            'LINFOMA HODGKIN',
            'LINFOMA NO HODGKIN EXTRANODAL',
            'CANCER DE ENDOMETRIO',
            'LINFOMA NO HODGKIN',
            'CANCER DE MAMA IN SITU',
            'MELANOMA',
            'CANCER GERMINAL DE OVARIO',
            'MIELOLOLIPOMA',
            'CARCINOIDE',
            'CANCER DE CERVIX',
            'CANCER DE PANCREAS',
            'HEMANGIOMA DE COLUMNA VERTE L3',
            'NODULO MAMARIO',
            'CANCER DE RECTO',
            'ADENOCARCINOMA DE RECTO E B',
            'MELANOMA BRESLOW',
            'MELANOMA NODULAR',
            'MELANOMA DE COROIDES',
            'MELANOMA MALIGNO',
            'LINFOMA NO HODGKIN E IV',
            'LINFOMA NO HODGKIN E III',
            'LINFOMA SNC',
            'LINFOMA',
            'LINFOMA GASTRICO',
            'LINFOMA INTESTINO DELGADO',
            'NODULO TIROIDE',
            'CANCER DE CERVIX ESTADIO III',
            'CANCER DE CERVIX ESTADIO IV',
            'CANCER DE COLON',
            'CARCINOIDE DE COLON',
            'ADENOCARCINOMA DE COLON',
            'CANCER DE OVARIO ESTADIO III',
            'CANCER DE OVARIO ESTADIO I',
            'CANCER DE OVARIO ESTADIO IV',
            'ADENOCARCINOMA DE OVARIO',
            'CANCER DE PULMON',
            'CANCER DE PULMON ESTADIO III',
            'CANCER DE PULMON ESTADIO IV',
            'CARCINOMA DE PULMON',
            'CANCER DE PROSTATA ESTADIO IV',
            'ADENOCARCINOMA DE PROSTATA',
            'CANCER DE PROSTATA ESTADIO II',
            'CANCER DE PROSTATA ESTADIO III',
            'CANCER DE ENDOMETRIO I',
            'CANCER DE ENDOMETRIO II',
            'CANCER DE ENDOMETRIO III',
            'SARCOMA DEL ESTROMA ENDOMETRI0 II',
            'SEMINOMA DE TESTICULO',
            'TNS DE TESTICULO',
            'CANCER DE TESTICULO',
            'CARCINOMA DE TESTICULO',
            'CANCER DE VEJIGA',
            'CANCER DE HIPOFARINGE',
            'CANCER DE ESOFAGO E II',
            'CANCER DE ESOFAGO E III',
            'CANCER DE ESOFAGO E IV',
            'CANCER EPIDERMOIDE DE ESOFAGO',
            'CANCER DE VAGINA',
            'CANCER DE VULVA',
            'ADENOCARCINOMA',
            'ADENOCARCINOMA GASTRICO',
            'ADENOCARCINOMA EN AXILA',
            'ADENOCARCINOMA PLEURAL',
            'ADENOCARCINOMA PERITONEALES',
            'CARCINOMA',
            'HEPATOCARCINOMA',
            'CARCINOMA BASOCELULAR',
            'CARCINOMA DUCTAL',
            'CELULAS',
            'CARCINOMA EPITELIAL',
            'CARCINOMA EPIDERMOIDE',
            'CANCER DE CABEZA Y CUELLO',
            'CARCINOMA DE CABEZA Y CUELLO',
            'CARCINOMA DE CELULAS',
            'CARCINOMA DE PAROTIDA',
            'CARCINOMA DE SENO',
            'CARCINOMA ESCAMOCELULAR',
            'CARCINOMA ESPINOCELULAR',
            'CARCINOMA DE LABIO',
            'CARCINOMA DE TABIQUE NASAL',
            'CARCINOMA LOBULAR INFILTRANTE',
            'CARCINOMA A CELULAS CLARAS',
            'CANCER DE AMIGDALA',
            'CANCER DE AMIGDALA ESTUDIO III',
            'CANCER DE PANCREAS ESTADIO III',
            'CANCER DE PANCREAS ESTADIO IV',
            'CANCER GASTRICO',
            'CANCER GASTRICO ESTUDIO III',
            'CANCER GASTRICO ESTUDIO IV',
            'CANCER GASTRICO ESTUDIO II',
            'CANCER DE LENGUA',
            'CANCER DE ANO / ANAL',
            'CANCER DE PULMON ESTADIO II',
            'CANCER BASOCELULAR',
            'CANCER DE RIÑON',
            'CANCER DE SUPRAGLOTIS',
            'HIPERNEFROMA',
            'GLIOBLASTOMA',
            'LEIMIOSARCOMA',
            'EPITELIOMA',
            'EPITELIOMA BASOCELULAR',
            'CARCINOMA CLOACOGENICO INFILTRANTE',
            'CANCER DE VESICULA',
            'CANCER DE ESTOMAGO',
            'RABDOMIOSARCOMA',
            'SARCOMA',
            'SARCOMA DE CADERA',
            'SARCOMA DE EWING E IV',
            'SARCOMA DE KAPOSI',
            'SARCOMA DE LIPOSARCOMA',
            'SARCOMA DE MULLERIANO',
            'TUMOR',
            'T DE CUELLO',
            'CANCER DE BIOPSIA',
            'CANCER EPIDERMOIDE DE PULMON',
            'CANCER EPIDERMOIDE DEL ALA DE LA NARIZ',
            'CANCER EPIDERMOIDE',
            'ANGIOPERICITOMA MALIGNO',
            'CANCER DE CUELLO UTERINO E II B',
            'CANCER RENAL',
            'CANCER RETROPERITONEAL',
            'CANCER DE TABIQUE NASAL',
            'LEUCEMIA LINFATICA',
            'CANCER DE CA DE PISO DE BOCA.',
            'CANCER DE CAVUM. PEDIR HC',
            'CANCER DE PAROTIDA',
            'CANCER DE PISO DE BOCA',
            'CANCER INDIFERENCIADO DE TIROIDES.',
            'ENFERMEDAD DE HOGDKIN',
            'EPIDERMOIDE SEMIDIF.DE LENGUA',
            'FIBROHISTIOCITOMA MALIGNO E IV',
            'LIPOSARCOMA MIXOIDE RETROPERITONEAL.',
            'MELANOMA COROIDEO',
            'MICOSIS FUNGOIDE GENERALIZADA.',
            'NEUROFIBROMA DE LSUP.',
            'OSTEOSARCOMA CALOTA D.',
            'T.HEMOPRRAGICO.MTS MULTIPLES',
            'TGNOSEMINOMATOSO EIV.',
            'TIMOMA',
            'OSTEOMIELITIS',
            'SIN DIAGNOSTICO',
            'MELANOMA DE PIEL',
            'OLIGODRENDROGLIOMA ANAPLASICO',
            'SIN DIAGNOSTICO',
            'CA DE PULMON NSC',
            'CA DE PULMON SC',
            'MESOTELIOMA',
            'WILMS',
            'CANCER DE INTESTINO DELGADO',
            'ENFERMEDAD DE PAGET',
            'CORDOMA',
            'LEIOMIOMA',
            'LEIMIOMA',
            'CARCINOMA DE GLANDULA SALIVALES',
            'CANCER DE LA UNION ESOFAGOGASTRICO',
            'CANCER DE LA REUNION RECTOSIGMOIDEA',
            'ENFERMEDAD DE CASTELMAN',
            'CARCINOMA DE QUISTE BRANQUIAL',
            'SARCOMA DEL ESTROMA ENDOMETRIAL',
            'GIST'
            ];

        foreach($patologias as $patologia)
        {
            Pathology::create([
                'name' => $patologia,
                'is_active' => 1,
                ]);
        }
    }
}
